// <auto-generated />
using System;
using DespachoJuridico.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DespachoJuridico.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DespachoJuridico.API.Models.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.BitacoraCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("BitacoraCambios");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.EtapaCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsDiasHabiles")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int?>("TerminoDias")
                        .HasColumnType("integer");

                    b.Property<string>("TipoJuicio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EtapasCatalogo");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.Expediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BancoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExpedienteRelacionadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Juzgado")
                        .HasColumnType("text");

                    b.Property<string>("Materia")
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("NumeroExpediente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParteDemandada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoJuicio")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioAsignadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("ExpedienteRelacionadoId");

                    b.HasIndex("UsuarioAsignadoId");

                    b.ToTable("Expedientes");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.HistorialEtapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Atendido")
                        .HasColumnType("boolean");

                    b.Property<int?>("EtapaCatalogoId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("RegistradoPorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EtapaCatalogoId");

                    b.HasIndex("ExpedienteId");

                    b.HasIndex("RegistradoPorId");

                    b.ToTable("HistorialEtapas");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinatarioEmail")
                        .HasColumnType("text");

                    b.Property<bool>("Enviada")
                        .HasColumnType("boolean");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HistorialEtapaId")
                        .HasColumnType("integer");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.HasIndex("HistorialEtapaId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.BitacoraCambio", b =>
                {
                    b.HasOne("DespachoJuridico.API.Models.Expediente", "Expediente")
                        .WithMany("Bitacora")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DespachoJuridico.API.Models.Usuario", "Usuario")
                        .WithMany("Bitacora")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.Expediente", b =>
                {
                    b.HasOne("DespachoJuridico.API.Models.Banco", "Banco")
                        .WithMany("Expedientes")
                        .HasForeignKey("BancoId");

                    b.HasOne("DespachoJuridico.API.Models.Usuario", "CreadoPor")
                        .WithMany("ExpedientesCreados")
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DespachoJuridico.API.Models.Expediente", "ExpedienteRelacionado")
                        .WithMany()
                        .HasForeignKey("ExpedienteRelacionadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DespachoJuridico.API.Models.Usuario", "UsuarioAsignado")
                        .WithMany("ExpedientesAsignados")
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Banco");

                    b.Navigation("CreadoPor");

                    b.Navigation("ExpedienteRelacionado");

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.HistorialEtapa", b =>
                {
                    b.HasOne("DespachoJuridico.API.Models.EtapaCatalogo", "EtapaCatalogo")
                        .WithMany("Historial")
                        .HasForeignKey("EtapaCatalogoId");

                    b.HasOne("DespachoJuridico.API.Models.Expediente", "Expediente")
                        .WithMany("Historial")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DespachoJuridico.API.Models.Usuario", "RegistradoPor")
                        .WithMany("HistorialRegistrado")
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtapaCatalogo");

                    b.Navigation("Expediente");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.Notificacion", b =>
                {
                    b.HasOne("DespachoJuridico.API.Models.Expediente", "Expediente")
                        .WithMany("Notificaciones")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DespachoJuridico.API.Models.HistorialEtapa", "HistorialEtapa")
                        .WithMany("Notificaciones")
                        .HasForeignKey("HistorialEtapaId");

                    b.Navigation("Expediente");

                    b.Navigation("HistorialEtapa");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.Banco", b =>
                {
                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.EtapaCatalogo", b =>
                {
                    b.Navigation("Historial");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.Expediente", b =>
                {
                    b.Navigation("Bitacora");

                    b.Navigation("Historial");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.HistorialEtapa", b =>
                {
                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("DespachoJuridico.API.Models.Usuario", b =>
                {
                    b.Navigation("Bitacora");

                    b.Navigation("ExpedientesAsignados");

                    b.Navigation("ExpedientesCreados");

                    b.Navigation("HistorialRegistrado");
                });
#pragma warning restore 612, 618
        }
    }
}
